// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykqmyzvfkdaybtwypdde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrcW15enZma2RheWJ0d3lwZGRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzE2MzAsImV4cCI6MjA3MDkwNzYzMH0.PCpXbjWrPUMuznq3ltmE6xHKoyDy-GEaakRJVdhnM7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});